/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CENG102_PROJE_2019_OTEL;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beyza
 */
public class AdminSayfasi extends javax.swing.JFrame {
    
    String connectionString = "jdbc:sqlserver://127.0.0.1; databaseName=OTEL_Proje_2019";
    String musteriID;
    int odaID;

    /**
     * Creates new form AdminSayfasi
     */
    public AdminSayfasi() throws InstantiationException, IllegalAccessException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sekmeler = new javax.swing.JTabbedPane();
        tumRezervasyonlar = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rezervasyonTablo = new javax.swing.JTable();
        tumMusteriler = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        musteriTablo = new javax.swing.JTable();
        rezGuncelle = new javax.swing.JPanel();
        odaid = new javax.swing.JLabel();
        musteriid = new javax.swing.JLabel();
        rezGuncelleUyari = new javax.swing.JLabel();
        girisTarihi = new javax.swing.JLabel();
        cikisTarihi = new javax.swing.JLabel();
        odadaKalanY = new javax.swing.JLabel();
        odadaKalanC = new javax.swing.JLabel();
        rezGuncelleButonu = new javax.swing.JButton();
        textOdaId = new javax.swing.JTextField();
        textMusteriId = new javax.swing.JTextField();
        textKalanY = new javax.swing.JTextField();
        textKalanC = new javax.swing.JTextField();
        textGiris = new javax.swing.JTextField();
        textCikis = new javax.swing.JTextField();
        yasUyari = new javax.swing.JLabel();
        kalınacakGun = new javax.swing.JLabel();
        textGun = new javax.swing.JTextField();
        musteriGuncelle = new javax.swing.JPanel();
        musteriGuncelleUyari = new javax.swing.JLabel();
        musTC = new javax.swing.JLabel();
        musAd = new javax.swing.JLabel();
        musSoyad = new javax.swing.JLabel();
        musYas = new javax.swing.JLabel();
        musMail = new javax.swing.JLabel();
        musMeslek = new javax.swing.JLabel();
        musTel = new javax.swing.JLabel();
        musCins = new javax.swing.JLabel();
        textTC = new javax.swing.JTextField();
        textAd = new javax.swing.JTextField();
        textSoyad = new javax.swing.JTextField();
        textYas = new javax.swing.JTextField();
        textMail = new javax.swing.JTextField();
        textMeslek = new javax.swing.JTextField();
        textTel = new javax.swing.JTextField();
        textCins = new javax.swing.JTextField();
        musGuncelleButonu = new javax.swing.JButton();
        rezSil = new javax.swing.JPanel();
        rezSilUyari = new javax.swing.JLabel();
        musteriId = new javax.swing.JLabel();
        odaId = new javax.swing.JLabel();
        textOdaID = new javax.swing.JTextField();
        textMusteriID = new javax.swing.JTextField();
        rezSilButonu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TcLabel = new javax.swing.JLabel();
        AdLabel = new javax.swing.JLabel();
        SoyadLabel = new javax.swing.JLabel();
        textMusTc = new javax.swing.JTextField();
        textMusAd = new javax.swing.JTextField();
        textMusSoyad = new javax.swing.JTextField();
        musSilUyari = new javax.swing.JLabel();
        musSilButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        sekmeler.setBackground(new java.awt.Color(213, 213, 255));
        sekmeler.setForeground(new java.awt.Color(153, 0, 102));
        sekmeler.setPreferredSize(new java.awt.Dimension(810, 425));

        rezervasyonTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rezervasyonTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rezervasyonTabloMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(rezervasyonTablo);

        javax.swing.GroupLayout tumRezervasyonlarLayout = new javax.swing.GroupLayout(tumRezervasyonlar);
        tumRezervasyonlar.setLayout(tumRezervasyonlarLayout);
        tumRezervasyonlarLayout.setHorizontalGroup(
            tumRezervasyonlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        tumRezervasyonlarLayout.setVerticalGroup(
            tumRezervasyonlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );

        sekmeler.addTab("TÜM REZERVASYONLAR", tumRezervasyonlar);

        musteriTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        musteriTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musteriTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(musteriTablo);

        javax.swing.GroupLayout tumMusterilerLayout = new javax.swing.GroupLayout(tumMusteriler);
        tumMusteriler.setLayout(tumMusterilerLayout);
        tumMusterilerLayout.setHorizontalGroup(
            tumMusterilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        tumMusterilerLayout.setVerticalGroup(
            tumMusterilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tumMusterilerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        sekmeler.addTab("TÜM MÜŞTERİLER", tumMusteriler);

        rezGuncelle.setBackground(new java.awt.Color(255, 204, 204));
        rezGuncelle.setPreferredSize(new java.awt.Dimension(805, 425));

        odaid.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        odaid.setText("Oda ID:");

        musteriid.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musteriid.setText("Müşteri ID:");

        rezGuncelleUyari.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        rezGuncelleUyari.setForeground(new java.awt.Color(255, 0, 51));
        rezGuncelleUyari.setText("Seçilen Rezervasyon Bilgilerini Güncelleyin...");

        girisTarihi.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        girisTarihi.setText("Giriş Tarihi:");

        cikisTarihi.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        cikisTarihi.setText("Çıkış Tarihi:");

        odadaKalanY.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        odadaKalanY.setText("Odada Kalan Yetişkin Sayısı:");

        odadaKalanC.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        odadaKalanC.setText("Odada Kalan Çocuk Sayısı:");

        rezGuncelleButonu.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        rezGuncelleButonu.setForeground(new java.awt.Color(94, 63, 140));
        rezGuncelleButonu.setText("GÜNCELLE");
        rezGuncelleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezGuncelleButonuActionPerformed(evt);
            }
        });

        yasUyari.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        yasUyari.setText("(12 yaşından küçük)");

        kalınacakGun.setText("Kalınacak Gün Sayısı:");

        javax.swing.GroupLayout rezGuncelleLayout = new javax.swing.GroupLayout(rezGuncelle);
        rezGuncelle.setLayout(rezGuncelleLayout);
        rezGuncelleLayout.setHorizontalGroup(
            rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rezGuncelleLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(rezGuncelleLayout.createSequentialGroup()
                            .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(musteriid, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(odaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textOdaId, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(textMusteriId)))
                        .addGroup(rezGuncelleLayout.createSequentialGroup()
                            .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(girisTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cikisTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(odadaKalanY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(odadaKalanC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(kalınacakGun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(76, 76, 76)
                            .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textKalanY, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(textKalanC)
                                .addComponent(textGiris)
                                .addComponent(textCikis)
                                .addComponent(textGun))))
                    .addComponent(rezGuncelleUyari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yasUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rezGuncelleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rezGuncelleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        rezGuncelleLayout.setVerticalGroup(
            rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rezGuncelleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rezGuncelleUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odaid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textOdaId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMusteriId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKalanY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odadaKalanY, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKalanC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odadaKalanC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yasUyari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girisTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cikisTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCikis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rezGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kalınacakGun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rezGuncelleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        sekmeler.addTab("REZERVASYON GÜNCELLE", rezGuncelle);

        musteriGuncelle.setBackground(new java.awt.Color(220, 220, 253));

        musteriGuncelleUyari.setBackground(new java.awt.Color(255, 255, 255));
        musteriGuncelleUyari.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        musteriGuncelleUyari.setForeground(new java.awt.Color(255, 0, 0));
        musteriGuncelleUyari.setText("Seçilen Müşteri Bilgilerini Güncelleyin...");

        musTC.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musTC.setText("Müşteri TC:");

        musAd.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musAd.setText("Müşteri Ad:");

        musSoyad.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musSoyad.setText("Müşteri Soyad:");

        musYas.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musYas.setText("Müşteri Yaş:");

        musMail.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musMail.setText("Müşteri Email:");

        musMeslek.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musMeslek.setText("Müşteri Meslek:");

        musTel.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musTel.setText("Müşteri Telefon:");

        musCins.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musCins.setText("Müşteri Cinsiyet:");

        musGuncelleButonu.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        musGuncelleButonu.setForeground(new java.awt.Color(102, 0, 102));
        musGuncelleButonu.setText("GÜNCELLE");
        musGuncelleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musGuncelleButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout musteriGuncelleLayout = new javax.swing.GroupLayout(musteriGuncelle);
        musteriGuncelle.setLayout(musteriGuncelleLayout);
        musteriGuncelleLayout.setHorizontalGroup(
            musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriGuncelleLayout.createSequentialGroup()
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musteriGuncelleLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(musteriGuncelleUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(musteriGuncelleLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musAd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musTC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musYas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musMail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musMeslek, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musTel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musCins, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTC)
                            .addComponent(textAd)
                            .addComponent(textSoyad)
                            .addComponent(textYas)
                            .addComponent(textMail)
                            .addComponent(textMeslek)
                            .addComponent(textTel)
                            .addComponent(textCins, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musteriGuncelleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(musGuncelleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        musteriGuncelleLayout.setVerticalGroup(
            musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriGuncelleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(musteriGuncelleUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musTC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musAd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musYas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textYas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musMail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musMeslek, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMeslek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musTel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musteriGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musCins, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musGuncelleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        sekmeler.addTab("MÜŞTERİ GÜNCELLE", musteriGuncelle);

        rezSil.setBackground(new java.awt.Color(253, 219, 184));

        rezSilUyari.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        rezSilUyari.setForeground(new java.awt.Color(255, 0, 0));
        rezSilUyari.setText("Seçtiğiniz Müşterinin Kaydını Silmek İstiyorsanız SİL'e Tıklayın...");

        musteriId.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musteriId.setText("Müşteri ID:");

        odaId.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        odaId.setText("Oda ID:");

        rezSilButonu.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        rezSilButonu.setForeground(new java.awt.Color(93, 54, 132));
        rezSilButonu.setText("SİL");
        rezSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezSilButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rezSilLayout = new javax.swing.GroupLayout(rezSil);
        rezSil.setLayout(rezSilLayout);
        rezSilLayout.setHorizontalGroup(
            rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rezSilLayout.createSequentialGroup()
                .addGroup(rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rezSilButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(rezSilLayout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addGroup(rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(odaId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(musteriId, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textOdaID, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(textMusteriID))
                            .addGap(21, 21, 21)))
                    .addGroup(rezSilLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(rezSilUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rezSilLayout.setVerticalGroup(
            rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rezSilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rezSilUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odaId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textOdaID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rezSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMusteriID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(rezSilButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        sekmeler.addTab("REZERVASYON SİL", rezSil);

        jPanel1.setBackground(new java.awt.Color(207, 196, 196));

        TcLabel.setText("Müşteri TC:");

        AdLabel.setText("Müşteri Ad:");

        SoyadLabel.setText("Müşteri Soyad:");

        musSilUyari.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        musSilUyari.setForeground(new java.awt.Color(255, 51, 0));
        musSilUyari.setText("Seçilen Müşteriyi Silmek İstiyorsanız SİL'e Tıklayın...");

        musSilButonu.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        musSilButonu.setForeground(new java.awt.Color(102, 0, 102));
        musSilButonu.setText("SİL");
        musSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musSilButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SoyadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(AdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textMusTc)
                            .addComponent(textMusAd)
                            .addComponent(textMusSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(musSilUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(musSilButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(musSilUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMusTc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMusAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoyadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMusSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(musSilButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        sekmeler.addTab("MÜŞTERİ SİL", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sekmeler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sekmeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Pencere açılır açılmaz rezervasyon ve müşteri tablolarını dolduruyor
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        rezervasyonTablosuDoldur();
        musteriTablosuDoldur();
    }//GEN-LAST:event_formWindowOpened

    // Rezervasyon tablosuna tıklandığında üstünce olduğu rezervasyonun bilgilerini doldurması için Rezervasyon Güncelle ve Rezervasyon Sil metodları çağrılıyor
    private void rezervasyonTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rezervasyonTabloMouseClicked
        try
        {
            // TODO add your handling code here:
            rezGuncellemeSayfasiDoldur();
        }catch (SQLException ex) {
            Logger.getLogger(AdminSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            rezSilmeSayfasiDoldur();
        }catch (SQLException ex)
        {
            Logger.getLogger(AdminSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rezervasyonTabloMouseClicked

    // Rezervasyon tablosundan seçien rezervasyonun bilgilerini Rezervasyon Sil sekmesine dolduruyor
    private void rezSilmeSayfasiDoldur() throws SQLException
    {
        int idx = rezervasyonTablo.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) rezervasyonTablo.getModel();
        odaID = Integer.parseInt(model.getValueAt(idx, 0).toString());
        System.out.println(""+odaID);
        String query = "SELECT odaID, musteriID FROM tblMusteriKayit WHERE odaID="+odaID;
        System.out.println(""+query);

        DBHandler dbh;
        try
        {            
            dbh = new DBHandler(connectionString,"beyza","bnk");
            ResultSet rs = dbh.executeQuery(query);
            while(rs.next())
            {
                textOdaID.setText(rs.getString(1));
                textMusteriID.setText(rs.getString(2));
                break;
            }
            dbh.close();
        }catch (SQLException ex)
        {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    // Rezervasyon tablosundan seçilen rezervasyonun bilgilerini Rezervasyon Güncelle sekmesine dolduruyor
    private void rezGuncellemeSayfasiDoldur() throws SQLException
    {
        int idx = rezervasyonTablo.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) rezervasyonTablo.getModel();
        odaID = Integer.parseInt(model.getValueAt(idx, 0).toString());
        System.out.println(""+odaID);
        String query = "SELECT * FROM tblMusteriKayit WHERE odaID="+odaID;
        System.out.println(""+query);

        DBHandler dbh;
        try
        {
            dbh = new DBHandler(connectionString,"beyza","bnk");
            ResultSet rs = dbh.executeQuery(query);
            while(rs.next())
            {
                textOdaId.setText(rs.getString(1));
                textMusteriId.setText(rs.getString(2));
                textKalanY.setText(rs.getString(3));
                textKalanC.setText(rs.getString(4));
                textGiris.setText(rs.getString(5));
                textCikis.setText(rs.getString(6));
                textGun.setText(rs.getString(7));
                break;
            }
            dbh.close();
        }catch (SQLException ex)
        {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    // Müşteri tablosunda üzerine basılan kişinin bilgilerini Müşteri Sil sekmesine doldurur
    private void musSilmeSayfasiDoldur()
    {
        int idx = musteriTablo.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) musteriTablo.getModel();
        musteriID = (String) model.getValueAt(idx, 0).toString();
        System.out.println(""+musteriID);
        String query = "SELECT musteriID, musteriAd, musteriSoyad FROM tblMusteri WHERE musteriID="+musteriID;
        System.out.println(""+query);

        DBHandler dbh;
        try
        {            
            dbh = new DBHandler(connectionString,"beyza","bnk");
            ResultSet rs = dbh.executeQuery(query);
            while(rs.next())
            {
                textMusTc.setText(rs.getString(1));
                textMusAd.setText(rs.getString(2));
                textMusSoyad.setText(rs.getString(3));
                break;
            }
            dbh.close();
        }catch (SQLException ex)
        {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    // Müşteri tablosundan üstüne basılan kişinin bilgilerini Müşteri Güncelle sekmesine dolduruyor
    private void musteriGuncelleSayfasiDoldur()
    {
        // Tabloda seçilen kişinin müşteriID'sini (TC nosunu)alıyor 
        int idx = musteriTablo.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) musteriTablo.getModel();
        musteriID = (String) model.getValueAt(idx, 0);
        System.out.println(""+musteriID);
        String query = "SELECT * FROM tblMusteri WHERE musteriID="+musteriID;
        System.out.println(""+query);

        DBHandler dbh;
        try
        {
            dbh = new DBHandler(connectionString,"beyza","bnk");
            ResultSet rs = dbh.executeQuery(query);
            while(rs.next())
            {
                textTC.setText(rs.getString(1));
                textAd.setText(rs.getString(2));
                textSoyad.setText(rs.getString(3));
                textYas.setText(rs.getString(4));
                textMail.setText(rs.getString(5));
                textMeslek.setText(rs.getString(6));
                textTel.setText(rs.getString(7));
                textCins.setText(rs.getString(8));
                break;
            }
            dbh.close();
        }catch (SQLException ex)
        {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    // Rezervasyon Güncelle sekmesinde yaptığımız değişiklikleri veritabanına kaydediyor
    private void rezGuncelleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezGuncelleButonuActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE tblMusteriKayit SET odaID='"+textOdaId.getText()+"', musteriID='"+ textMusteriId.getText()+"', odadaKalanYetiskin='"+ textKalanY.getText()+"', odadaKalanCocuk='"+ textKalanC.getText()+"', girisTarihi='"+ textGiris.getText()+"', cikisTarihi='"+ textCikis.getText()+"', kalınacakGun='"+textGun.getText()+"' WHERE odaID="+odaID;
       
        try {
            DBHandler dbh = new DBHandler(connectionString,"beyza","bnk");
            int rows = dbh.executeNonQuery(query);
            System.out.println("Rows affected by  "+rows);
            dbh.close();
            rezervasyonTablosuDoldur(); // Rezervasyonu güncelledikten sonra yeni bilgilerle tabloyu tekrar doldurması için bu metodu çağırdık
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rezGuncelleButonuActionPerformed

    // TextFieldlara dolan bilgiye sahip rezervasonu siliyor, bir kez açıp kapayınca silindiği görülüyor
    private void rezSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezSilButonuActionPerformed
        // TODO add your handling code here:
        odaID = Integer.parseInt(textOdaId.getText().toString());
        System.out.println(""+odaID);
        // Seçili odaID'sine sahip rezervasyonu veritabanından siliyor
        String query = "DELETE FROM tblMusteriKayit WHERE odaID="+odaID; 
        System.out.println(""+query);

        DBHandler dbh;
        try
        {
            dbh = new DBHandler(connectionString,"beyza","bnk");
            ResultSet rs = dbh.executeQuery(query);
            dbh.close();
            rezervasyonTablosuDoldur(); // Rezervasyon silindikten sonra rezervasyon listesinin tekrar güncel bilgilerle doldurulması için çağırdık
        }catch (SQLException ex)
        {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rezSilButonuActionPerformed

    // Müşteri Tablosuna basılldığında üstüne basılan kişinin bilgilerini Müşteri Güncelle sayfasına dolduruyor
    private void musteriTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriTabloMouseClicked
        // TODO add your handling code here:
        musteriGuncelleSayfasiDoldur();
        musSilmeSayfasiDoldur();
    }//GEN-LAST:event_musteriTabloMouseClicked

    // Müşteri Güncelle sekmesinde müşteri bilgileri üzerinde yaptığımız değişiklikleri veritabanına kaydediyor
    private void musGuncelleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musGuncelleButonuActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE tblMusteri SET musteriID='"+textTC.getText()+"', musteriAd='"+ textAd.getText()+"', musteriSoyad='"+ textSoyad.getText()+"', musteriYas='"+ textYas.getText()+"', musteriEmail='"+ textMail.getText()+"', musteriMeslek='"+ textMeslek.getText()+"', musteriTelefon='"+ textTel.getText()+"', musteriCins='"+ textCins.getText()+"' WHERE musteriID="+musteriID;
       
        try {
            DBHandler dbh = new DBHandler(connectionString,"beyza","bnk");
            int rows = dbh.executeNonQuery(query);
            System.out.println("Rows affected by  "+rows);
            dbh.close();
            musteriTablosuDoldur();
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_musGuncelleButonuActionPerformed

    // Müşteri tablosunda üzerine tıklanan kişiyi veritabanından siliyor
    private void musSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musSilButonuActionPerformed
        // TODO add your handling code here:
        musteriID = (String) textOdaId.getText().toString();
        System.out.println(""+musteriID);
        // Seçili musteiID'sine sahip müşteriyi veritabanından siliyor
        String query = "DELETE FROM tblMusteri WHERE musteriID="+musteriID; 
        System.out.println(""+query);

        DBHandler dbh;
        try
        {
            dbh = new DBHandler(connectionString,"beyza","bnk");
            ResultSet rs = dbh.executeQuery(query);
            dbh.close();
            musteriTablosuDoldur(); // Rezervasyon silindikten sonra rezervasyon listesinin tekrar güncel bilgilerle doldurulması için çağırdık
        }catch (SQLException ex)
        {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_musSilButonuActionPerformed

    // Tüm Müşteriler sekmesindeki tabloyu müşteri bilgileriyle dolduruyor
    private void musteriTablosuDoldur()
    {
        DBHandler dbh = null;
        try
        {
        String query = "SELECT * FROM tblMusteri";
        dbh = new DBHandler(connectionString,"beyza","bnk");
        ResultSet rs = dbh.executeQuery(query);
        int count=0;
        DefaultTableModel model = new DefaultTableModel();
        String[] column = {"Müşteri TC", "Müşteri Adı","Müşteri Soyadı", "Müşteri Yaşı", "Müşteri Email", "Müşteri Mesleği", "Müşteri Telefon No", "Müşteri Cinsiyeti"}; // 6 öğeden oluşan tablo başlıkları
        model.setColumnIdentifiers(column);
        musteriTablo.setModel(model);
        
        while(rs.next())
        {
            System.out.printf("%-35s\t", rs.getObject(1));
            model.addRow(new Object []{ rs.getString(1),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
            count++;
        }
        }catch (Exception e)
        {
            System.out.println(""+e.getMessage());                
        }
        finally
        {
            try
            {
                dbh.close();
            }catch (SQLException ex)
            {
                //Logger.getLogger(tabbedPAneNewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Tüm Rezervasyonlar sekmesindeki tabloyu rezervasyon bilgileriyle dolduruyor
    private void rezervasyonTablosuDoldur()
    {
        DBHandler dbh = null; // DBHandler sınıfı database işlemlerimizde yardımcı olur
        try
        {
        String query = "SELECT  * FROM tblMusteriKayit";
        dbh = new DBHandler(connectionString, "beyza", "bnk");
        ResultSet rs = dbh.executeQuery(query);
        int count=0;
        DefaultTableModel model = new DefaultTableModel();
        String[] column = {"Oda ID","Müşteri TC","Odada Kalan Yetişkin","Odada Kalan Çocuk","Giriş Tarihi","Çıkış Tarihi","Kalınacak Gün"};
        model.setColumnIdentifiers(column);
        rezervasyonTablo.setModel(model);
        while(rs.next())
        {
            System.out.printf("%-35s\t", rs.getObject(1));
            model.addRow(new Object []{ rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getInt(4),rs.getString(5),rs.getString(6),rs.getInt(7)});
            count++;
        }
        }catch (Exception e)
        {
                    System.out.println(""+e.getMessage());
        }
        finally
        {
            try
            {
                dbh.close();
            }catch (SQLException ex)
            {
                //Logger.getLogger(tabbedPAneNewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try {
                    new AdminSayfasi().setVisible(true);
                } catch (InstantiationException ex) {
                    Logger.getLogger(AdminSayfasi.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(AdminSayfasi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdLabel;
    private javax.swing.JLabel SoyadLabel;
    private javax.swing.JLabel TcLabel;
    private javax.swing.JLabel cikisTarihi;
    private javax.swing.JLabel girisTarihi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel kalınacakGun;
    private javax.swing.JLabel musAd;
    private javax.swing.JLabel musCins;
    private javax.swing.JButton musGuncelleButonu;
    private javax.swing.JLabel musMail;
    private javax.swing.JLabel musMeslek;
    private javax.swing.JButton musSilButonu;
    private javax.swing.JLabel musSilUyari;
    private javax.swing.JLabel musSoyad;
    private javax.swing.JLabel musTC;
    private javax.swing.JLabel musTel;
    private javax.swing.JLabel musYas;
    private javax.swing.JPanel musteriGuncelle;
    private javax.swing.JLabel musteriGuncelleUyari;
    private javax.swing.JLabel musteriId;
    private javax.swing.JTable musteriTablo;
    private javax.swing.JLabel musteriid;
    private javax.swing.JLabel odaId;
    private javax.swing.JLabel odadaKalanC;
    private javax.swing.JLabel odadaKalanY;
    private javax.swing.JLabel odaid;
    private javax.swing.JPanel rezGuncelle;
    private javax.swing.JButton rezGuncelleButonu;
    private javax.swing.JLabel rezGuncelleUyari;
    private javax.swing.JPanel rezSil;
    private javax.swing.JButton rezSilButonu;
    private javax.swing.JLabel rezSilUyari;
    private javax.swing.JTable rezervasyonTablo;
    private javax.swing.JTabbedPane sekmeler;
    private javax.swing.JTextField textAd;
    private javax.swing.JTextField textCikis;
    private javax.swing.JTextField textCins;
    private javax.swing.JTextField textGiris;
    private javax.swing.JTextField textGun;
    private javax.swing.JTextField textKalanC;
    private javax.swing.JTextField textKalanY;
    private javax.swing.JTextField textMail;
    private javax.swing.JTextField textMeslek;
    private javax.swing.JTextField textMusAd;
    private javax.swing.JTextField textMusSoyad;
    private javax.swing.JTextField textMusTc;
    private javax.swing.JTextField textMusteriID;
    private javax.swing.JTextField textMusteriId;
    private javax.swing.JTextField textOdaID;
    private javax.swing.JTextField textOdaId;
    private javax.swing.JTextField textSoyad;
    private javax.swing.JTextField textTC;
    private javax.swing.JTextField textTel;
    private javax.swing.JTextField textYas;
    private javax.swing.JPanel tumMusteriler;
    private javax.swing.JPanel tumRezervasyonlar;
    private javax.swing.JLabel yasUyari;
    // End of variables declaration//GEN-END:variables
}