/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CENG102_PROJE_2019_OTEL;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author beyza
 */
public class Anasayfa extends javax.swing.JFrame {

    String connectionString = "jdbc:sqlserver://127.0.0.1; databaseName=OTEL_Proje_2019";
    /**
     * Creates new form Anasayfa
     */
    public Anasayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sekmeler = new javax.swing.JTabbedPane();
        anasayfa = new javax.swing.JPanel();
        hosgeldiniz = new javax.swing.JLabel();
        anasayfaArka = new javax.swing.JLabel();
        odalarimiz = new javax.swing.JPanel();
        tekResim = new javax.swing.JLabel();
        ciftResim = new javax.swing.JLabel();
        aileResim = new javax.swing.JLabel();
        balayiResim = new javax.swing.JLabel();
        kralResim = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tekBilgi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ciftBilgi = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        aileBilgi = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        balayiBilgi = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        kralBilgi = new javax.swing.JTextArea();
        rezervasyonSayfasi = new javax.swing.JPanel();
        musAd = new javax.swing.JLabel();
        musTc = new javax.swing.JLabel();
        musYas = new javax.swing.JLabel();
        musTel = new javax.swing.JLabel();
        musMeslek = new javax.swing.JLabel();
        musMail = new javax.swing.JLabel();
        textMusAd = new javax.swing.JTextField();
        textMusYas = new javax.swing.JTextField();
        textMusMail = new javax.swing.JTextField();
        textMusMeslek = new javax.swing.JTextField();
        textMusTel = new javax.swing.JTextField();
        textMusTc = new javax.swing.JTextField();
        rezYap = new javax.swing.JButton();
        musSoyad = new javax.swing.JLabel();
        textMusSoyad = new javax.swing.JTextField();
        musCins = new javax.swing.JLabel();
        textMusCins = new javax.swing.JTextField();
        adminSayfasi = new javax.swing.JPanel();
        kulAdi = new javax.swing.JLabel();
        sifre = new javax.swing.JLabel();
        kulAdiAlani = new javax.swing.JTextField();
        girisButonu = new javax.swing.JButton();
        sifreAlani = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uyari = new javax.swing.JLabel();
        adminArka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sekmeler.setBackground(new java.awt.Color(212, 212, 252));
        sekmeler.setForeground(new java.awt.Color(153, 0, 102));

        anasayfa.setLayout(null);

        hosgeldiniz.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        hosgeldiniz.setForeground(new java.awt.Color(255, 255, 255));
        hosgeldiniz.setText("OTELİMİZE HOŞGELDİNİZ!  :)");
        anasayfa.add(hosgeldiniz);
        hosgeldiniz.setBounds(120, 70, 310, 40);

        anasayfaArka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CENG102_PROJE_2019_OTEL/1.jpg"))); // NOI18N
        anasayfa.add(anasayfaArka);
        anasayfaArka.setBounds(0, 0, 810, 400);

        sekmeler.addTab("ANASAYFA", anasayfa);

        odalarimiz.setBackground(new java.awt.Color(188, 217, 173));
        odalarimiz.setLayout(null);

        tekResim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tekResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CENG102_PROJE_2019_OTEL/tek kişilik.jpg"))); // NOI18N
        odalarimiz.add(tekResim);
        tekResim.setBounds(10, 20, 150, 120);

        ciftResim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciftResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CENG102_PROJE_2019_OTEL/çift kişilik.jpg"))); // NOI18N
        odalarimiz.add(ciftResim);
        ciftResim.setBounds(170, 20, 150, 120);

        aileResim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aileResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CENG102_PROJE_2019_OTEL/aile.jpg"))); // NOI18N
        odalarimiz.add(aileResim);
        aileResim.setBounds(330, 20, 150, 120);

        balayiResim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balayiResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CENG102_PROJE_2019_OTEL/balayı.jpg"))); // NOI18N
        odalarimiz.add(balayiResim);
        balayiResim.setBounds(490, 20, 140, 120);

        kralResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CENG102_PROJE_2019_OTEL/kral.jpg"))); // NOI18N
        odalarimiz.add(kralResim);
        kralResim.setBounds(640, 20, 160, 120);

        tekBilgi.setColumns(20);
        tekBilgi.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        tekBilgi.setRows(5);
        tekBilgi.setText("STANDART ODA\n\n1 Yetişkin + 1 Çocuk\n20 Metrekare\n1 Tek Kişilik Yatak\nDuş\nOrman Manzarası\nÇocuk Fiyatı: 50\nYetişkin Fiyatı: 100");
        jScrollPane2.setViewportView(tekBilgi);

        odalarimiz.add(jScrollPane2);
        jScrollPane2.setBounds(10, 160, 150, 180);

        ciftBilgi.setColumns(20);
        ciftBilgi.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        ciftBilgi.setRows(5);
        ciftBilgi.setText("SUİT ODA\n\n2 Yetişkin + 1 Çocuk\n30 Metrekare\n1 Çift Kişilik Yatak\nDuş\nDeiz Manzarası\nÇocuk Fiyatı: 75\nYetişkin Fiyatı: 150");
        jScrollPane3.setViewportView(ciftBilgi);

        odalarimiz.add(jScrollPane3);
        jScrollPane3.setBounds(170, 160, 150, 180);

        aileBilgi.setColumns(20);
        aileBilgi.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        aileBilgi.setRows(5);
        aileBilgi.setText("AİLE ODASI\n\n4 Yetişkin veya 2 Yetişkin + 2 Çocuk\n50 Metrekare\n1 Çift Kişilik Yatak + ek\nDuş ve Küvet\nOrman Manzarası\nÇocuk Fiyatı: 150\nYetişkin Fiyatı: 300");
        jScrollPane4.setViewportView(aileBilgi);

        odalarimiz.add(jScrollPane4);
        jScrollPane4.setBounds(330, 160, 150, 180);

        balayiBilgi.setColumns(20);
        balayiBilgi.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        balayiBilgi.setRows(5);
        balayiBilgi.setText("BALAYI ODASI\n\n2 Yetişkin\n40 Metrekare\n1 Çift Kişilik Yatak\nDuş ve Küvet\nDeniz Manzarası\nÇocuk Kalamaz\nYetişkin Fiyatı: 500");
        jScrollPane5.setViewportView(balayiBilgi);

        odalarimiz.add(jScrollPane5);
        jScrollPane5.setBounds(490, 160, 140, 180);

        kralBilgi.setColumns(20);
        kralBilgi.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        kralBilgi.setRows(5);
        kralBilgi.setText("KRAL ODASI\n\n6 Yetişkin + 2 Yetişkin + 4 Çocuk\n80 Metrekare\n3 Çift Kişilik Yatak + ek\nDuş ve Jakuzi\nOrman ve Deniz Manzarası\nÇocuk Fiyatı: 500\nYetişkin Fiyatı: 1000");
        jScrollPane6.setViewportView(kralBilgi);

        odalarimiz.add(jScrollPane6);
        jScrollPane6.setBounds(640, 160, 160, 180);

        sekmeler.addTab("ODALARIMIZ", odalarimiz);

        rezervasyonSayfasi.setBackground(new java.awt.Color(249, 209, 249));
        rezervasyonSayfasi.setLayout(null);

        musAd.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musAd.setText("Müşteri Ad:");
        rezervasyonSayfasi.add(musAd);
        musAd.setBounds(30, 90, 110, 30);

        musTc.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musTc.setText("Müşteri TC:");
        rezervasyonSayfasi.add(musTc);
        musTc.setBounds(30, 40, 120, 30);

        musYas.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musYas.setText("Müşteri Yaş:");
        rezervasyonSayfasi.add(musYas);
        musYas.setBounds(30, 190, 90, 30);

        musTel.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musTel.setText("Müşteri Telefon:");
        rezervasyonSayfasi.add(musTel);
        musTel.setBounds(380, 140, 110, 30);

        musMeslek.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musMeslek.setText("Müşteri Meslek:");
        rezervasyonSayfasi.add(musMeslek);
        musMeslek.setBounds(380, 90, 100, 30);

        musMail.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musMail.setText("Müşteri Email:");
        rezervasyonSayfasi.add(musMail);
        musMail.setBounds(380, 40, 120, 30);
        rezervasyonSayfasi.add(textMusAd);
        textMusAd.setBounds(140, 90, 140, 30);
        rezervasyonSayfasi.add(textMusYas);
        textMusYas.setBounds(140, 190, 140, 30);
        rezervasyonSayfasi.add(textMusMail);
        textMusMail.setBounds(510, 40, 140, 30);
        rezervasyonSayfasi.add(textMusMeslek);
        textMusMeslek.setBounds(510, 90, 140, 30);
        rezervasyonSayfasi.add(textMusTel);
        textMusTel.setBounds(510, 140, 140, 30);
        rezervasyonSayfasi.add(textMusTc);
        textMusTc.setBounds(140, 40, 140, 30);

        rezYap.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        rezYap.setForeground(new java.awt.Color(102, 0, 102));
        rezYap.setText("MÜŞTERİ EKLE");
        rezYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezYapActionPerformed(evt);
            }
        });
        rezervasyonSayfasi.add(rezYap);
        rezYap.setBounds(600, 240, 150, 40);

        musSoyad.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musSoyad.setText("Müşteri Soyad:");
        rezervasyonSayfasi.add(musSoyad);
        musSoyad.setBounds(30, 140, 100, 30);
        rezervasyonSayfasi.add(textMusSoyad);
        textMusSoyad.setBounds(140, 140, 140, 30);

        musCins.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        musCins.setText("Müşteri Cinsiyet:");
        rezervasyonSayfasi.add(musCins);
        musCins.setBounds(380, 190, 100, 30);
        rezervasyonSayfasi.add(textMusCins);
        textMusCins.setBounds(510, 190, 140, 30);

        sekmeler.addTab("MÜŞTERİ EKLE", rezervasyonSayfasi);

        adminSayfasi.setLayout(null);

        kulAdi.setBackground(new java.awt.Color(255, 204, 204));
        kulAdi.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        kulAdi.setForeground(new java.awt.Color(102, 0, 102));
        kulAdi.setText("Kullanıcı Adı:");
        adminSayfasi.add(kulAdi);
        kulAdi.setBounds(200, 110, 110, 35);

        sifre.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        sifre.setForeground(new java.awt.Color(102, 0, 102));
        sifre.setText("Şifre:");
        adminSayfasi.add(sifre);
        sifre.setBounds(200, 160, 110, 32);
        adminSayfasi.add(kulAdiAlani);
        kulAdiAlani.setBounds(350, 110, 160, 30);

        girisButonu.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        girisButonu.setForeground(new java.awt.Color(94, 64, 139));
        girisButonu.setText("GİRİŞ");
        girisButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButonuActionPerformed(evt);
            }
        });
        adminSayfasi.add(girisButonu);
        girisButonu.setBounds(450, 230, 90, 30);
        adminSayfasi.add(sifreAlani);
        sifreAlani.setBounds(350, 160, 160, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        adminSayfasi.add(jPanel1);
        jPanel1.setBounds(190, 110, 130, 90);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(uyari);

        adminSayfasi.add(jPanel2);
        jPanel2.setBounds(200, 50, 370, 30);

        adminArka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CENG102_PROJE_2019_OTEL/2.jpg"))); // NOI18N
        adminSayfasi.add(adminArka);
        adminArka.setBounds(0, 0, 810, 400);

        sekmeler.addTab("ADMİN PANELİ", adminSayfasi);

        getContentPane().add(sekmeler);
        sekmeler.setBounds(0, 0, 810, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Admin Panelinde kullanıcı adı ve şifre doğru girildiğinde AdminSayfasi frameini açıyor
    private void girisButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButonuActionPerformed
        // TODO add your handling code here:
        String kulAdi = kulAdiAlani.getText();
        String sifre = new String(sifreAlani.getPassword());
        String uyariYazisi = "Kullanıcı adı veya şifre yanlış! Tekrar deneyiniz.";
        if(kulAdi.equals("beyza") && sifre.equals("nur"))
        {
            try {
                (new AdminSayfasi()).setVisible(true);
            } catch (InstantiationException ex) {
                Logger.getLogger(Anasayfa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Anasayfa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            uyari.setText(uyariYazisi);
        }
    }//GEN-LAST:event_girisButonuActionPerformed

    // Girilen bilgilerini musteri tablosuna kaydediyor
    private void musteriKaydet()
    {
        // TODO add your handling code here:
        String musteriTC = (String) textMusTc.getText();
        String musteriAd = (String) textMusAd.getText();
        String musteriSoyad = (String) textMusSoyad.getText();
        int musteriYas = Integer.parseInt(textMusYas.getText());
        String musteriMail = (String) textMusMail.getText();
        String musteriMeslek = (String) textMusMeslek.getText();  
        String musteriTel = (String) textMusTel.getText();
        String musteriCins = (String) textMusCins.getText();
        
        String query = String.format("INSERT INTO tblMusteri VALUES('%s','%s','%s',%d,'%s','%s','%s','%s')", musteriTC, musteriAd, musteriSoyad, musteriYas, musteriMail, musteriMeslek, musteriTel, musteriCins);
        System.out.println(""+query);
        try {
            DBHandler dbh = new DBHandler(connectionString,"beyza","bnk");
            ResultSet rs = dbh.executeQuery(query);
            dbh.close();
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(AdminSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private void rezYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezYapActionPerformed
        // TODO add your handling code here:
        musteriKaydet();
        new RezervasyonEkle().setVisible(true);
    }//GEN-LAST:event_rezYapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminArka;
    private javax.swing.JPanel adminSayfasi;
    private javax.swing.JTextArea aileBilgi;
    private javax.swing.JLabel aileResim;
    private javax.swing.JPanel anasayfa;
    private javax.swing.JLabel anasayfaArka;
    private javax.swing.JTextArea balayiBilgi;
    private javax.swing.JLabel balayiResim;
    private javax.swing.JTextArea ciftBilgi;
    private javax.swing.JLabel ciftResim;
    private javax.swing.JButton girisButonu;
    private javax.swing.JLabel hosgeldiniz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea kralBilgi;
    private javax.swing.JLabel kralResim;
    private javax.swing.JLabel kulAdi;
    private javax.swing.JTextField kulAdiAlani;
    private javax.swing.JLabel musAd;
    private javax.swing.JLabel musCins;
    private javax.swing.JLabel musMail;
    private javax.swing.JLabel musMeslek;
    private javax.swing.JLabel musSoyad;
    private javax.swing.JLabel musTc;
    private javax.swing.JLabel musTel;
    private javax.swing.JLabel musYas;
    private javax.swing.JPanel odalarimiz;
    private javax.swing.JButton rezYap;
    private javax.swing.JPanel rezervasyonSayfasi;
    private javax.swing.JTabbedPane sekmeler;
    private javax.swing.JLabel sifre;
    private javax.swing.JPasswordField sifreAlani;
    private javax.swing.JTextArea tekBilgi;
    private javax.swing.JLabel tekResim;
    private javax.swing.JTextField textMusAd;
    private javax.swing.JTextField textMusCins;
    private javax.swing.JTextField textMusMail;
    private javax.swing.JTextField textMusMeslek;
    private javax.swing.JTextField textMusSoyad;
    private javax.swing.JTextField textMusTc;
    private javax.swing.JTextField textMusTel;
    private javax.swing.JTextField textMusYas;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables
}
